baseURL = "http://ituonecosia.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "5"
summaryLength = "15"
theme = "bigspring"
title = "ITU on Ecosia"
[markup.goldmark.renderer]
unsafe = true
