[de]
contentDir = "content/deutsch"
copyright = "Istanbul Technical University on Ecosia | 2021"
footer_content = "#ITUonEcosia"
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "En"
title = "ITU on Ecosia"
weight = 2
[en]
contentDir = "content/english"
copyright = "Istanbul Technical University on Ecosia | 2021"
footer_content = "Istanbul Technical University on Ecosia"
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "Tr"
title = "ITU on Ecosia"
weight = "1"
