[de]
contentDir = "content/deutsch"
copyright = "Istanbul Technical University on Ecosia | 2021"
footer_content = "#ITUonEcosia"
footer_menu_left = "Ecosia"
footer_menu_middle = "Ecosia on Campus"
footer_menu_right = "ITU on Ecosia"
languageName = "En"
title = "ITU on Ecosia"
weight = 2
[en]
contentDir = "content/english"
copyright = "Istanbul Technical University on Ecosia | 2021"
footer_content = "#ITUonEcosia"
footer_menu_left = "Ecosia"
footer_menu_middle = "Ecosia on Campus"
footer_menu_right = "ITU on Ecosia"
languageName = "Tr"
title = "ITU on Ecosia"
weight = "1"
