[[footer_left]]
name = "About"
url = "https://info.ecosia.org/about"
[[footer_left]]
name = "How Ecosia Works"
url = "https://info.ecosia.org/what"
[[footer_left]]
name = "FAQ"
url = "https://ecosia.zendesk.com/hc/en-us"
[[footer_middle]]
name = "About"
url = "https://explore.ecosia.org/ecosia-on-campus"
[[footer_middle]]
name = "Blog"
url = "https://blog.ecosia.org/ecosia-on-campus-more-unis/"
[[footer_right]]
name = "FAQ"
url = "https://ituonecosia.netlify.app/faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Blog"
url = "blog"
weight = 2
[[main]]
name = "Contact"
url = "contact"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
