[[footer_left]]
name = "Ecosia Nasıl Çalışır"
url = "https://info.ecosia.org/what"
[[footer_left]]
name = "Hakkında"
url = "https://info.ecosia.org/about"
[[footer_left]]
name = "SSS"
url = "https://ecosia.zendesk.com/hc/en-us"
[[footer_middle]]
name = "Hakkında"
url = "https://explore.ecosia.org/ecosia-on-campus"
[[footer_middle]]
name = "Blog"
url = "https://blog.ecosia.org/ecosia-on-campus-more-unis/"
[[footer_right]]
name = "SSS"
url = "https://ituonecosia.netlify.app/faq"
[[main]]
name = "Anasayfa"
url = "/"
weight = 1
[[main]]
name = "Blog"
url = "blog"
weight = 2
[[main]]
name = "İletişim"
url = "contact"
weight = 4
[[main]]
name = "SSS"
url = "faq"
weight = 5
