author = "ITU on Ecosia"
contact_form_action = "mailto:ituonecosia@gmail.com"
description = "Istanbul Technical University on Ecosia"
logo = "images/logo.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "İndir"
link = "https://www.ecosia.org/"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
