author = "ITU on Ecosia"
contact_form_action = "mailto:ituonecosia@gmail.com"
description = "Istanbul Technical University on Ecosia"
logo = "images/ecosia-logo-3.png"
logo_width = "150px"
[navigation_button]
enable = true
label = "ITU on Ecosia URL"
link = "https://www.ecosia.org/ITU"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/ituonecosia/"
title = "instagram"
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
